---
title: "Research Metrics Report"
subtitle: |
  Daniel P. Haerther Center for Conservation and Research  
  John G. Shedd Aquarium
output: html_document
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.height = 4, fig.width = 6)

# Set cutoff date
cutoff <- Sys.Date()
#cutoff <- as.Date("2020-03-31")
```

```{bash, include = FALSE, eval = FALSE}
# Download latest research metrics from Sharepoint document
wget -O data/Research_Metrics.xlsx https://sheddaquarium.sharepoint.com/:x:/s/Conservation/EVrWpG_x6o9OofNYVkuEnr4B3vsvxgYDNDamVStTRXVWNA?download=1
```

```{r, include = FALSE, eval = TRUE}
# Scrape latest citation counts from Google Scholar
source('R/scrape_gs.R')
```

```{r}
library(readxl)
library(tidyverse)
library(lubridate)
library(janitor)
library(ggthemes)
library(RColorBrewer)

## ggplot theme
theme_custom <- function() {
  theme_few() +
  theme(legend.title=element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.justification = "center",
        legend.text = element_text(size = 14),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 14),
        strip.text = element_text(size = 18),
        plot.title = element_text(size = 20, hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
}

## ggplot color palette
```

```{r}
# Import historical summary metrics (2018 and earlier)
pre2019 <- read_xlsx("data/pre2019_summary.xlsx")
```

```{r}
# Import latest research metrics (from 2019 on -- downloaded from SharePoint)
metrics <- read_xlsx("data/Research_Metrics.xlsx") %>%
  # Clean numbers in Quantity column (e.g., remove non-numbers such as "~")
  mutate(Quantity = as.numeric(str_extract(Quantity, "[0-9]+"))) %>%
  # Bin events into years and quarters
  mutate(Year = year(EventDate),
         Quarter = paste0("Q", quarter(EventDate)))

# Cutoff date (see above; set to today's date or end of quarter for report preparation)
metrics <- metrics %>%
   filter(EventDate <= cutoff)
```

```{r}
# Citations

# Import citation count data
cites <- read_tsv("data/citation_counts.txt") %>%
  filter(date <= cutoff)
```

```{r}
latest <- tail(cites, 1)
```

*****

#### *Current publication metrics:*
##### **Publications:** `r latest$total_pubs`  
##### **Citations:** `r latest$total_cites`  
##### **h-index:** `r latest$h_index`  
##### **i10-index:** `r latest$i10_index` 

*****

```{r}
# Publications

pubsumm <- metrics %>%
  filter(Category == "Publication") %>%
  group_by(Year, Quarter) %>%
  summarize(Quantity = n()) %>%
  bind_rows(filter(pre2019, Category == "Publications")) %>%
  select(Year, Quarter, Quantity) %>%
  ungroup() %>%
  complete(Year, Quarter, fill = list(Quantity = 0))

ggplot(pubsumm, aes(x = Quarter, y = Quantity, fill = factor(Year))) +
  facet_grid(~ Year) +
  geom_bar(stat = "identity", alpha = 0.7) +
  geom_text(aes(label = ifelse(Quantity == 0, "", Quantity)), color = "white", nudge_y = -0.25) +
  theme_custom() +
  theme(legend.position = "none") +
  labs(x = "", y = "", title = "Number of Scientific Publications")
```

```{r}
# Tidy and calculate new citations by quarter
cites <- cites %>%
  mutate(Year = year(date),
         Quarter = paste0("Q", quarter(date))) %>%
  group_by(Year, Quarter) %>%
  distinct(date, .keep_all = TRUE) %>%       # Remove duplicated dates
  filter(date == max(date)) %>%              # Get latest date with available data in each quarter
  ungroup() %>%
  arrange(Year, Quarter) %>%                    # Order by year and quarter
  mutate(Citations = total_cites - lag(total_cites)) %>%  # Calculate number of new citations in quarter
  select(Year, Quarter, Citations) %>%
  ungroup() %>%
  complete(Year = full_seq(c(2019, max(Year)), 1), Quarter, fill = list(Citations = 0))
  
# Combine with pre2019 data
citesumm <- pre2019 %>%
  filter(Category == "Citations") %>%
  spread(Category, Quantity) %>%
  bind_rows(cites)

ggplot(citesumm, aes(x = Quarter, y = Citations, fill = factor(Year))) +
  facet_grid(~ Year) +
  geom_bar(stat = "identity", alpha = 0.7) +
  geom_text(aes(label = ifelse(Citations == 0, "", Citations)), color = "white", nudge_y = -5) +
  theme_custom() +
  theme(legend.position = "none") +
  labs(x = "", y = "", title = "Number of Citations")
```

```{r}
# Media opportunities

mediasumm <- metrics %>%
  filter(Category == "Media opportunity") %>%
  group_by(Year, Quarter) %>%
  summarize(Quantity = n()) %>%
  bind_rows(filter(pre2019, Category == "Media opportunity")) %>%
  select(Year, Quarter, Quantity) %>%
  ungroup() %>%
  complete(Year, Quarter, fill = list(Quantity = 0))
  

ggplot(mediasumm, aes(x = Quarter, y = Quantity, fill = factor(Year))) +
  facet_grid(~ Year) +
  geom_bar(stat = "identity", alpha = 0.7) +
  geom_text(aes(label = ifelse(Quantity == 0, "", Quantity)), color = "white", nudge_y = -0.5) +
  theme_custom() +
  theme(legend.position = "none") +
  labs(x = "", y = "", title = "Number of Print/Media Opportunities")
```


```{r}
# Presentations

pressumm <- metrics %>%
  filter(Category == "Presentation") %>%
  group_by(Year, Quarter) %>%
  summarize(Quantity = n()) %>%
  bind_rows(filter(pre2019, Category == "Presentation")) %>%
  select(Year, Quarter, Quantity) %>%
  ungroup() %>%
  complete(Year, Quarter, fill = list(Quantity = 0))

ggplot(pressumm, aes(x = Quarter, y = Quantity, fill = factor(Year))) +
  facet_grid(~ Year) +
  geom_bar(stat = "identity", alpha = 0.7) +
  geom_text(aes(label = ifelse(Quantity == 0, "", Quantity)), color = "white", nudge_y = -0.75) +
  theme_custom() +
  theme(legend.position = "none") +
  labs(x = "", y = "", title = "Number of Presentations")
```


```{r}
# Total disseminations

dissem <- bind_rows(`Scientific Pubs.        ` = pubsumm, 
                    `Print/Media        ` = mediasumm,
                    `Presentations        ` = pressumm,
                    .id = "Category") %>%
  mutate(QY = interaction(Quarter, Year))

ggplot(dissem, aes(x = Quarter, y = Quantity, fill = Category)) +
  facet_grid(~ Year) +
  geom_bar(stat = "identity", alpha = 0.7) +
  geom_text(aes(y = Quantity - 1, label = ifelse(Quantity == 0, "", Quantity)), 
            position = "stack", color = "white") +
  theme_custom() +
  theme(legend.spacing.x = unit(1, "mm"),
        legend.box.margin=margin(-30,0,0,0)) +
  labs(x = "", y = "", title = "Number of Dissemination Outputs")
```


```{r}
# Citizen/stakeholder engagement -- unique individuals

engagement.unique.ind <- metrics %>%
  filter(Category == "Citizen/stakeholder engagement") %>%
  group_by(Year, Quarter) %>%
  summarize(Quantity = sum(Quantity, na.rm = TRUE)) %>%
  bind_rows(filter(pre2019, Category == "Citizen/stakeholder engagement")) %>%
  select(Year, Quarter, Quantity) %>%
  ungroup() %>%
  complete(Year, Quarter, fill = list(Quantity = 0))

ggplot(engagement.unique.ind, aes(x = Quarter, y = Quantity, fill = factor(Year))) +
  facet_grid(~ Year) +
  geom_bar(stat = "identity", alpha = 0.7) +
  geom_text(aes(label = ifelse(Quantity == 0, "", Quantity)), color = "white", nudge_y = -10) +
  theme_custom() +
  theme(legend.position = "none") +
  labs(x = "", y = "", title = "Number of Citizen Scientists/Stakeholders")
```

```{r}
# Total engagement effort in person*hours

engagement.person.hours <- metrics %>%
  filter(Category == "Citizen/stakeholder engagement") %>%
  group_by(Year, Quarter) %>%
  summarize(Quantity = sum(Effort, na.rm = TRUE)) %>%
  select(Year, Quarter, Quantity) %>%
  ungroup() %>%
  complete(Year, Quarter, fill = list(Quantity = 0))

ggplot(engagement.person.hours, aes(x = Quarter, y = Quantity, fill = factor(Year))) +
  facet_grid(~ Year) +
  geom_bar(stat = "identity", alpha = 0.7) +
  geom_text(aes(label = ifelse(Quantity == 0, "", Quantity)), color = "white", nudge_y = -200) +
  theme_custom() +
  theme(legend.position = "none") +
  labs(x = "", y = "Total person*hours", title = "Citizen/Stakeholder Engagement Effort")
```


```{r}
# Field days

fdaysumm <- metrics %>%
  filter(Category == "Field research") %>%
  group_by(Year, Quarter) %>%
  summarize(Quantity = sum(Quantity)) %>%
  bind_rows(filter(pre2019, Category == "Field research")) %>%
  select(Year, Quarter, Quantity) %>%
  ungroup() %>%
  complete(Year, Quarter, fill = list(Quantity = 0))

ggplot(fdaysumm, aes(x = Quarter, y = Quantity, fill = factor(Year))) +
  facet_grid(~ Year) +
  geom_bar(stat = "identity", alpha = 0.7) +
  geom_text(aes(label = ifelse(Quantity == 0, "", Quantity)), color = "white", nudge_y = -5) +
  theme_custom() +
  theme(legend.position = "none") +
  labs(x = "", y = "", title = "Number of Field Days")
```